#ASCII文件路径  # 风攻角: 文件路径集合
#如果测点太多导致要分多次测量，路径应按照批次排序
dataFile:
  0: ["./P_1/000-1_0.CSV", "./P_2/000-1_0.CSV"]
  15: ["./P_1/015-1_0.CSV", "./P_2/015-1_0.CSV"]
  30: ["./P_1/030-1_0.CSV", "./P_2/030-1_0.CSV"]
  45: ["./P_1/045-1_0.CSV", "./P_2/045-1_0.CSV"]
  60: ["./P_1/060-1_0.CSV", "./P_2/060-1_0.CSV"]
  75: ["./P_1/075-1_0.CSV", "./P_2/075-1_0.CSV"]
  90: ["./P_1/090-1_0.CSV", "./P_2/090-1_0.CSV"]
  105: ["./P_1/105-1_0.CSV", "./P_2/105-1_0.CSV"]
  120: ["./P_1/120-1_0.CSV", "./P_2/120-1_0.CSV"]
  135: ["./P_1/135-1_0.CSV", "./P_2/135-1_0.CSV"]
  150: ["./P_1/150-1_0.CSV", "./P_2/150-1_0.CSV"]
  165: ["./P_1/165-1_0.CSV", "./P_2/165-1_0.CSV"]
  180: ["./P_1/180-1_0.CSV", "./P_2/180-1_0.CSV"]
  195: ["./P_1/195-1_0.CSV", "./P_2/195-1_0.CSV"]
  210: ["./P_1/210-1_0.CSV", "./P_2/210-1_0.CSV"]
  225: ["./P_1/225-1_0.CSV", "./P_2/225-1_0.CSV"]
  240: ["./P_1/240-1_0.CSV", "./P_2/240-1_0.CSV"]
  255: ["./P_1/255-1_0.CSV", "./P_2/255-1_0.CSV"]
  270: ["./P_1/270-1_0.CSV", "./P_2/270-1_0.CSV"]
  285: ["./P_1/285-1_0.CSV", "./P_2/285-1_0.CSV"]
  300: ["./P_1/300-1_0.CSV", "./P_2/300-1_0.CSV"]
  315: ["./P_1/315-1_0.CSV", "./P_2/315-1_0.CSV"]
  330: ["./P_1/330-1_0.CSV", "./P_2/330-1_0.CSV"]
  345: ["./P_1/345-1_0.CSV", "./P_2/345-1_0.CSV"]

#扫描阀信息   # 扫描阀编号: 测点数量
scanner:
  851: 64
  853: 64
  854: 64
  855: 64
  857: 64
  
#扫描次数
scanTimes: 2

#链接表格，将测压阀的测点序号对应至自定义的测点名称
scannerLinkfile: ['scanner_link_1.xlsx','scanner_link_2.xlsx']

#定义皮托管在链接表格中的名称
pitotTubesLinkName: ['pitot_1','pitot_2']

# 采样频率(Hz)
samplingFrequency: 256

# 采样时间(s)
samplingTime: 60
